version: "3.9"

services:
  ninja-backend:
    container_name: ninja_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env
    depends_on:
      - ninja-db
    networks:
      - backend
    restart: on-failure
  ninja-db:
    container_name: ninja_db
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty123
    networks:
      - backend
    restart: on-failure
networks:
  backend:
    name: backend
    external: true
volumes:
  pg_data:


